import { defineStore } from 'pinia'
import { ref, computed } from 'vue'

const translations = {
  'pt-BR': {
    flag: '🇧🇷',
    label: 'Português',
    welcome: 'Bem-vindo!',
    tapToStart: 'Toque para começar sua compra',
    startOrder: 'INICIAR COMPRA',
    backToHome: 'Voltar ao início',
    back: 'Voltar',
    chooseQuantity: 'Escolher quantidade',
    viewCart: 'VER CARRINHO',
    cartEmpty: 'Seu carrinho está vazio',
    loadingProducts: 'Carregando produtos...',
    noProducts: 'Nenhum produto nesta categoria',
    tryOtherCategory: 'Escolha outra categoria na barra lateral',
    addToCart: 'ADICIONAR AO CARRINO',
    product: 'produto',
    products: 'produtos',
    addedToCart: 'adicionado!',
    yourCart: 'Seu Carrinho',
    item: 'item',
    items: 'itens',
    viewProducts: 'VER PRODUTOS',
    subtotal: 'Subtotal',
    discount: 'Desconto',
    total: 'Total',
    finalizeOrder: 'FINALIZAR PEDIDO',
    continueShopping: '← Continuar comprando',
    payment: 'Pagamento',
    choosePayment: 'Escolha a forma de pagamento',
    totalToPay: 'Total a pagar:',
    confirmPayment: 'CONFIRMAR PAGAMENTO',
    confirmPaymentWith: 'Confirmar pagamento via',
    paymentError: 'Erro ao processar pagamento. Tente novamente.',
    processingPayment: 'Processando pagamento',
    followPinpad: 'Siga as instruções no pinpad...',
    scanPixQr: 'Escaneie o QR Code PIX',
    scanPixHint: 'Abra o app do seu banco e escaneie o código abaixo',
    paymentNotApproved: 'Pagamento não aprovado',
    tryAgain: 'Tentar novamente',
    endTransaction: 'ENCERRAR',
    backToMenu: 'MENU INICIAL',
    processingHelp: 'Aguarde a confirmação do pagamento. Não feche esta tela.',
    purchaseDone: 'Compra realizada!',
    orderNumber: 'Número da compra',
    pickupCode: 'Código de autorização',
    printing: 'Imprimindo comprovante...',
    printSuccess: 'Comprovante impresso com sucesso!',
    printError: 'Erro na impressão:',
    backIn: 'Voltando ao início em',
    seconds: 's',
    secondsUnit: 'segundos',
    backToStart: 'VOLTAR AO INÍCIO',
    sessionEnded: 'Sessão encerrada',
    inactivityExpired: 'Seu tempo de inatividade expirou.',
    redirectingIn: 'Redirecionando em',
    stillThere: 'Você ainda está aí?',
    continueShoppingBtn: 'CONTINUAR COMPRANDO',
    sessionWillEnd: 'Sua sessão será encerrada',
    online: 'Online',
    offline: 'Sem conexão',
    reviseOrder: 'Revise seu pedido',
    quantity: 'Quantidade:',
    notesOptional: 'Observações (opcional)',
    notesPlaceholder: 'Ex: Sem embalagem, cor azul...',
    unavailable: 'Indisponível',
    notesPrefix: 'Obs:',
    removeItem: 'Remover',
    moreItems: 'mais',
    loadingPaymentMethods: 'Carregando formas de pagamento...',
    noPaymentMethods: 'Nenhuma forma de pagamento disponível. Chame um atendente.',
    paymentMethodsError: 'Não foi possível carregar os métodos de pagamento.',
    transactionCode: 'Código da transação',
    nsuLabel: 'NSU',
    unitPrice: 'un.',
    backToCart: 'VOLTAR AO CARRINHO',
    retryLoad: 'TENTAR NOVAMENTE',
    cancelOrder: 'CANCELAR PEDIDO',
    printFailedHint: 'Anote o código acima ou chame um atendente.',
    changeLanguage: 'Mudar idioma',
  },
  'en-US': {
    flag: '🇺🇸',
    label: 'English',
    welcome: 'Welcome!',
    tapToStart: 'Tap to start your order',
    startOrder: 'START ORDER',
    backToHome: 'Back to home',
    back: 'Back',
    chooseQuantity: 'Choose quantity',
    viewCart: 'VIEW CART',
    cartEmpty: 'Your cart is empty',
    loadingProducts: 'Loading products...',
    noProducts: 'No products in this category',
    tryOtherCategory: 'Choose another category in the sidebar',
    addToCart: 'ADD TO CART',
    product: 'product',
    products: 'products',
    addedToCart: 'added!',
    yourCart: 'Your Cart',
    item: 'item',
    items: 'items',
    viewProducts: 'VIEW PRODUCTS',
    subtotal: 'Subtotal',
    discount: 'Discount',
    total: 'Total',
    finalizeOrder: 'CHECKOUT',
    continueShopping: '← Continue shopping',
    payment: 'Payment',
    choosePayment: 'Choose payment method',
    totalToPay: 'Total to pay:',
    confirmPayment: 'CONFIRM PAYMENT',
    confirmPaymentWith: 'Confirm payment via',
    paymentError: 'Payment failed. Please try again.',
    processingPayment: 'Processing payment',
    followPinpad: 'Follow the instructions on the pinpad...',
    scanPixQr: 'Scan the PIX QR Code',
    scanPixHint: 'Open your bank app and scan the code below',
    paymentNotApproved: 'Payment not approved',
    tryAgain: 'Try again',
    endTransaction: 'CANCEL',
    backToMenu: 'MAIN MENU',
    processingHelp: 'Wait for payment confirmation. Do not close this screen.',
    purchaseDone: 'Purchase complete!',
    orderNumber: 'Order number',
    pickupCode: 'Authorization code',
    printing: 'Printing receipt...',
    printSuccess: 'Receipt printed successfully!',
    printError: 'Print error:',
    backIn: 'Returning to home in',
    seconds: 's',
    secondsUnit: 'seconds',
    backToStart: 'BACK TO HOME',
    sessionEnded: 'Session ended',
    inactivityExpired: 'Your session expired due to inactivity.',
    redirectingIn: 'Redirecting in',
    stillThere: 'Are you still there?',
    continueShoppingBtn: 'CONTINUE SHOPPING',
    sessionWillEnd: 'Your session will end',
    online: 'Online',
    offline: 'Offline',
    reviseOrder: 'Review your order',
    quantity: 'Quantity:',
    notesOptional: 'Notes (optional)',
    notesPlaceholder: 'E.g.: No packaging, blue color...',
    unavailable: 'Unavailable',
    notesPrefix: 'Note:',
    removeItem: 'Remove',
    moreItems: 'more',
    loadingPaymentMethods: 'Loading payment methods...',
    noPaymentMethods: 'No payment methods available. Please ask for assistance.',
    paymentMethodsError: 'Could not load payment methods.',
    transactionCode: 'Transaction code',
    nsuLabel: 'NSU',
    unitPrice: 'ea.',
    backToCart: 'BACK TO CART',
    retryLoad: 'TRY AGAIN',
    cancelOrder: 'CANCEL ORDER',
    printFailedHint: 'Write down the code above or ask for assistance.',
    changeLanguage: 'Change language',
  },
  'es-ES': {
    flag: '🇪🇸',
    label: 'Español',
    welcome: '¡Bienvenido!',
    tapToStart: 'Toca para comenzar tu compra',
    startOrder: 'INICIAR COMPRA',
    backToHome: 'Volver al inicio',
    back: 'Volver',
    chooseQuantity: 'Elegir cantidad',
    viewCart: 'VER CARRITO',
    cartEmpty: 'Tu carrito está vacío',
    loadingProducts: 'Cargando productos...',
    noProducts: 'Ningún producto en esta categoría',
    tryOtherCategory: 'Elige otra categoría en la barra lateral',
    addToCart: 'AGREGAR AL CARRITO',
    product: 'producto',
    products: 'productos',
    addedToCart: 'agregado!',
    yourCart: 'Tu Carrito',
    item: 'artículo',
    items: 'artículos',
    viewProducts: 'VER PRODUCTOS',
    subtotal: 'Subtotal',
    discount: 'Descuento',
    total: 'Total',
    finalizeOrder: 'FINALIZAR PEDIDO',
    continueShopping: '← Seguir comprando',
    payment: 'Pago',
    choosePayment: 'Elige la forma de pago',
    totalToPay: 'Total a pagar:',
    confirmPayment: 'CONFIRMAR PAGO',
    confirmPaymentWith: 'Confirmar pago vía',
    paymentError: 'Error al procesar el pago. Inténtalo de nuevo.',
    processingPayment: 'Procesando pago',
    followPinpad: 'Sigue las instrucciones en el pinpad...',
    scanPixQr: 'Escanee el código QR PIX',
    scanPixHint: 'Abra la app de su banco y escanee el código',
    paymentNotApproved: 'Pago no aprobado',
    tryAgain: 'Intentar de nuevo',
    endTransaction: 'CANCELAR',
    backToMenu: 'MENÚ INICIAL',
    processingHelp: 'Espere la confirmación del pago. No cierre esta pantalla.',
    purchaseDone: '¡Compra realizada!',
    orderNumber: 'Número de compra',
    pickupCode: 'Código de autorización',
    printing: 'Imprimiendo comprobante...',
    printSuccess: '¡Comprobante impreso con éxito!',
    printError: 'Error de impresión:',
    backIn: 'Volviendo al inicio en',
    seconds: 's',
    secondsUnit: 'segundos',
    backToStart: 'VOLVER AL INICIO',
    sessionEnded: 'Sesión finalizada',
    inactivityExpired: 'Tu sesión expiró por inactividad.',
    redirectingIn: 'Redirigiendo en',
    stillThere: '¿Sigues ahí?',
    continueShoppingBtn: 'SEGUIR COMPRANDO',
    sessionWillEnd: 'Tu sesión terminará',
    online: 'En línea',
    offline: 'Sin conexión',
    reviseOrder: 'Revisa tu pedido',
    quantity: 'Cantidad:',
    notesOptional: 'Observaciones (opcional)',
    notesPlaceholder: 'Ej.: Sin embalaje, color azul...',
    unavailable: 'No disponible',
    notesPrefix: 'Obs:',
    removeItem: 'Eliminar',
    moreItems: 'más',
    loadingPaymentMethods: 'Cargando formas de pago...',
    noPaymentMethods: 'No hay formas de pago disponibles. Pide ayuda a un empleado.',
    paymentMethodsError: 'No se pudieron cargar los métodos de pago.',
    transactionCode: 'Código de transacción',
    nsuLabel: 'NSU',
    unitPrice: 'u.',
    backToCart: 'VOLVER AL CARRITO',
    retryLoad: 'INTENTAR DE NUEVO',
    cancelOrder: 'CANCELAR PEDIDO',
    printFailedHint: 'Anota el código de arriba o pide ayuda a un empleado.',
    changeLanguage: 'Cambiar idioma',
  },
}

const localeOrder = ['pt-BR', 'en-US', 'es-ES']

export const useLanguageStore = defineStore('language', () => {
  const currentLocale = ref('pt-BR')

  const t = computed(() => translations[currentLocale.value] || translations['pt-BR'])

  const currentFlag = computed(() => t.value.flag)
  const currentLabel = computed(() => t.value.label)

  function cycleLanguage() {
    const idx = localeOrder.indexOf(currentLocale.value)
    const next = localeOrder[(idx + 1) % localeOrder.length]
    currentLocale.value = next
  }

  function setLocale(locale) {
    if (translations[locale]) {
      currentLocale.value = locale
    }
  }

  return {
    currentLocale,
    t,
    currentFlag,
    currentLabel,
    cycleLanguage,
    setLocale,
    localeOrder,
    translations,
  }
})
